### ISSUE TITLE
can not print chinese character "张"

### ISSUE THREAD

**Issue by puma007** [oneplus1000/gopdfsample#1]
I use your library for generating PDF，but it can not print chinese character "张"，other chinese characters can print,why? 
I refer to your sample code,and add the chinese font wts11.ttf.
`pdf.AddTTFFont("HDZB_5", "../ttf/wts11.ttf")
pdf.SetFont("HDZB_5", "", 14)`

**Comment by oneplus1000** [comment]
dup of https://github.com/signintech/gopdf/issues/34
